### ISSUE TITLE
What is the difference between it and metrics.net?

### ISSUE THREAD

**Issue by landonzeng** [AppMetrics/AppMetrics#217]
What is the difference between it and metrics.net?

**Comment by alhardy** [comment]
App Metrics was forked when I needed a .net core implementation and was not able to get any traction on that, I did also provided a POC.

There has been a lot of refactoring and features added to App Metrics since.

I contributed the OWIN adapter to Metrics.NET some time ago since I found it a very useful library, however I wanted to modernise and extend it freely once the original author unfortunately left us, and found it difficult to get guidance and PRs accepted (no criticism to the owners who inherited the project, they have been kind enough in trying to keep it alive)

**Comment by landonzeng** [comment]
Thanks

**Comment by ramonsmits** [comment]
@alhardy AppMetrics is a fork of Metrics.NET, but which? I see https://github.com/Recognos/Metrics.NET which seems to be a fork of https://github.com/etishor/Metrics.NET

At what version of Metrics.NET was the AppMetrics fork created?

Metrics.NET has a very simple dashboard to look at metrics which seems missing for AppMetrics, is that correct?
