### ISSUE TITLE
Creating Gauge events aggregates them forever

### ISSUE THREAD

**Issue by oreporan** [AppMetrics/AppMetrics#250]
We're using AppMetrics + Promotheus

First we call  `Measure.Gauge.SetValue(gaugeOptions, metricTags, value);`

While One of our `metricTags` is a GUID of the object which set the metric.

We have the GetMetrics endpoint which looks like this:

```C#
  var snapshot = _metrics.Snapshot.Get();
            using (var stream = new MemoryStream())
            {
                var formatter = new MetricsPrometheusTextOutputFormatter();
                await formatter.WriteAsync(stream, snapshot);

                var result = Encoding.UTF8.GetString(stream.ToArray());
                return result;
            }
```

What we see is that every metric that the GAUGE ever wrote is still there in the response. 
My expectation was that each time we'd get the snapshot, that it would flush out any previous data that was aggregated.

So for example in the /metrics response I see:

`application_some_data{id="1da7e7af-aee1-4f3d-a406-e47f5a8fd57d"} 1`
`application_some_data{id="1cfaa3ca-954c-4bf2-a422-36990a9eb6da"} 1`

and still a few hours later while getting /metrics these 2 metrics are still there

I'm guessing we're doing some wrong, or thats just how Appmetrics works.

**Comment by alhardy** [comment]
Yes, the gauge value will be kept until a recycle by design. 

What is your use case for resetting the value after reporting it?

**Comment by oreporan** [comment]
a) whats a recycle?

b)

We are sending snapshots of our system, so for example. Amount of active users (users that are logged in and fetching data actively). We do this by keeping a list of active users, and writing gauges like so:

```
active_user{id="1da7e7af-aee1-4f3d-a406-e47f5a8fd57d"} 1
active_user{id="1cfaa3ca-954c-4bf2-a422-36990a9eb6da"} 1
```

and then running a sum() of that in promotheus/grafana dashboard

If the data isn't reset, the sum() will only go up, while we want it to show the real amount of active users in the system

**Comment by alhardy** [comment]
> what's a recycle?

I mean since metrics are aggregated in memory, they would reset when the process restarts only.

> b)

Not exactly sure what is meant by "active" in your case, but it does sounds like you can use a counter which can automatically reset when flushed, see the docs on [`CounterOptions`](https://www.app-metrics.io/getting-started/metric-types/counters/#counter-reporting-options). 

A Gauge is more for metrics alternating in quantity by varying degrees such as CPU or Memory, therefore no real reason to have the ability to reset on reporting.

Have a look through the `App.Metrics.AspNetCore.Tracking` project and [InfluxDB Grafana dashboard](https://grafana.com/dashboards/2125) for similar cases to what I think you're after.

**Comment by alhardy** [comment]
How are you determining when a user becomes inactive? 

It sounds like using a Gauge this way i.e. setting to 1 then resetting on flushing, is saying the user is marked as inactive once the Gauge is reset, is the client continuously posting "active" to the server?

Getting a little off topic re App Metrics here though, the typical/intended case for a Gauge would not require resetting after it's flushed.
