### ISSUE TITLE
Metrics Error Tracking Middleware

### ISSUE THREAD

**Issue by chiragsh** [AppMetrics/AppMetrics#281]
Metrics Error Tracking Middleware does not increasing the counter value automatically. Is there a way to increment these counter manually or some configuration to increment it automatically ? 
Also i have to specify app.UseMetricsErrorTrackingMiddleware() separately  in my startup while i have also used app.UseMetricsAllMiddleware() there.

**Comment by alhardy** [comment]
At the moment those counters are automatically reset when read which is more useful when reporting. Ideally they shouldn't be reset when the `/metrics` endpoint is hit, however the prometheus reporter for example expects this since it scripts metrics via the endpoint.

Could make this configurable...

**Comment by Porl91** [comment]
Hi @alhardy, sorry if this isn't the place to ask this, but I just had a question based on your last reply in 2018. Is it expected behaviour that if you have multiple reporters configured (e.g. Console & InfluxDB), the first report causes any metric options with `ResetOnReporting` set to `true` to be reset for all subsequent reports?

**Comment by alhardy** [comment]
Yep this is expected right now in the case of using multiple reporters. I haven't yet thought much about refactoring to change this behaviour, typically a single reporter is used
