### ISSUE TITLE
Logged in user attribute & drill-down

### ISSUE THREAD

**Issue by gvsrini** [AppMetrics/AppMetrics#300]
First things first... This is an awesome product - you are a one-man army!

I have two questions:
1. How can I add the logged in user/device metric to the route. I can see that tags can be used, but it's not very clear where/how to add it.
2. When I click on a chart (An endpoint for example), it will be good if we can configure other panels to also apply the same filter. For example, when I click on an Endpoint X all other endpoint panels will also filter by Endpoint X. ElasticSearch does this by default. But unfortunately, the current solution lacks support for latest version of ES 6.

These two features can be very useful for troubleshooting operational issues.

**Comment by alhardy** [comment]
Glad you find it useful, thanks for the comment!

1. You can find the documentation on tagging [here](https://www.app-metrics.io/getting-started/fundamentals/tagging-organizing/). If you are referring to the asp.net core middleware, it's not possible to modify the metric tags set by the middleware, you would have to implement your own equivelant middleware.
2. @russcam was going to be looking at updating the ES reporter to support the latest version of ES at some stage. Otherwise would you be willing to give it a crack?

**Comment by WalissonPires** [comment]
up
