### ISSUE TITLE
How do you change the quantiles used by a Timer?

### ISSUE THREAD

**Issue by ben-foster-cko** [AppMetrics/AppMetrics#331]
I would like only 0.50, 0.95 and 0.99.

**Comment by alhardy** [comment]
Default quantiles for histograms (used by timers) will also be recorded, this doesn't really cost much in terms of performance because they're simply calculated using the sample collected. You can filter out which quantiles are reported though, see https://www.app-metrics.io/getting-started/filtering-metrics/
