### ISSUE TITLE
LogLevel from Logging configuration section is ignored when logging

### ISSUE THREAD

**Issue by rgueldenpfennig** [AppMetrics/AppMetrics#346]
I noticed that all of the App.Metrics TRACE logs are being sent to the console stream even when the default log level defined in the Logging section of the "appsettings.json" is set to "Information".

In this [sample ASP.NET Core application](https://github.com/rgueldenpfennig/AppMetricsNLog) I'm using NLog to prove this behaviour. To avoid it you can outcomment line 21 in the "nlog.config" file.

It seems that also without the usage of NLog we got the same behaviour.

**Comment by snakefoot** [comment]
What happens if you change this line:

https://github.com/rgueldenpfennig/AppMetricsNLog/blob/e44e03ca7289b1fd663a42f3beef68ed98350583/AppMetricsNLogTest/nlog.config#L22

To this:

`<logger name="*" minLevel="Trace" writeTo="Console" />`

Always a good idea to read the [tutorial](https://github.com/NLog/NLog/wiki/Tutorial#configure-nlog-targets-for-output).

**Comment by snakefoot** [comment]
AppMetrics uses [LibLog](https://github.com/damianh/LibLog), so doesn't recognize logging-configuration in `appsettings.json`
