### ISSUE TITLE
Question: Support for arbiratry value series?

### ISSUE THREAD

**Issue by woodne** [AppMetrics/AppMetrics#473]
This may be a vague question, but would it be possible/sensible to implement a type of metric that just has a series of values? 

For example, say I have a process that is doing some asynchronous processing, and at the end, I would like to report the time it took. I _could_ use a histogram to report that, but it has issues with service restarts producing artifacts, and for some processes, I would like to have all of the datapoints stored in my database, so it can compute averages, percentiles, etc. 

What I would like, is a way to record values, and then during each reporting interval, it writes each one to the reporters (so multiple rows to influx, e.g.), then the values are flushed and wait for more values to be added. 

Does this make sense for the scope of this library?

**Comment by ElanHasson** [comment]
It sounds like you're proposing a simple pass-through to reporters. I really like this idea and think this would be a good fit for the library.

I've encountered this issue where a single timing value is posted to the histogram, and that value exceeds my SLA and alerts fire in grafana. The alerts continue to fire because the histogram isn't reset as the sample size = 1.

I may be using the library incorrectly for my use case, but it sounds like  this would solve it for me.

**Comment by cyberhck** [comment]
I also want this actually, I'm measuring my own time, some times length of a string which is a KPI for me, I just want one bare raw measurement which simply sends this data to grafana, nothing else,

**Comment by cyberhck** [comment]
is this closed because now there's a way to do the thing author described? Or simply not in the scope? A message would be helpful 🙂

**Comment by alhardy** [comment]
> but would it be possible/sensible to implement a type of metric that just has a series of values?
Isn't this just a Gauge?

@cyberhck could you elaborate more on the proposal?

**Comment by cyberhck** [comment]
I might be missing something. But here's my requirement (if I'm missing something, please let me know)
- I've an API endpoint, which gives me a short code for something (let's say it uses a SHA1 of public key, and gives least characters for which there's no collision)
- Public keys are rotated every 15 mins so I can remove the old short keys,
- any time there's a new short code calculated, I want to send a raw metric which is just a integer value which is length of that short code,

the reason is that it's my KPI to have shorter short codes. And I want to send this to my TSDB so I can show many dots (because this is distributed) on my graph, and once it crosses some value, I get a notification. Can gauge handle this? What if there was 2 api calls this minute, one had bigger and one had lower, I think gauge will just show a current value, or grafana can change the way it's shown?

**Comment by woodne** [comment]
I think that is accurate. The gauge would only flush values when they are observed, but the use case for this was to ensure all the values are flushed to the TSDB.
