### ISSUE TITLE
Health Checks to Metrics

### ISSUE THREAD

**Issue by RPrzepio** [AppMetrics/AppMetrics#543]
I really enjoy the library but I don't see an option in the newest version to push health-checks to metrics.
.net Core provides healthchecks, but is it possible to somehow maybe format it to Prometheus format?
I was looking for this option but couldn't find it in any repo.
Thanks!

**Comment by alhardy** [comment]
I've removed App Metrics health functionality given Microsoft now have an implementation. I see two options:
1. A push based approach where you could write a heath check publisher which iterates through health check results and record as guage metrics, you would then be able to leverage built in app metrics publishers
2. A pull based approach, since you mention Prometheus, you probably want to take this approach, you would just need to implement a health check formatter which writes health check results as Prom line protocol. See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1#customize-output
