### ISSUE TITLE
Migration from AppMetrics.Health

### ISSUE THREAD

**Issue by vanderleipires** [AppMetrics/AppMetrics#594]
I trying to find any documentation of how to migrate from AppMetrics.Health 3.2 to AppMetrics 4.x but can't find anything, i'm looking for something to replace the old `AddHealthChecks`, `AddHttpGetCheck` and custom health checks inheriting from `HealthCheck`as described here: https://alhardy.github.io/app-metrics-docs/getting-started/health-checks/index.html

Is there any way to write custom health check and http checks in the current version?

**Comment by alhardy** [comment]
Health Check functionality as been depricated since Microsoft have an equivelant implementation. MS check results can be recorded and published as metrics using App Metrics https://www.app-metrics.io/reporting/reporters/microsoft-health-checks/

You're looking at old documentation, from version 1. for latest documentation see https://www.app-metrics.io/
