### ISSUE TITLE
[Question] integration with System.Diagnostics.Metrics

### ISSUE THREAD

**Issue by EugeneKrapivin** [AppMetrics/AppMetrics#730]
Hey,

Is there any planned integration with the new [System.Diagnostics.Metrics](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/compare-metric-apis#systemdiagnosticsmetrics) package, or is this considered a competing implementation?

Thanks,
Eugene.

**Comment by dagophil** [comment]
I wonder the same thing. We migrated a lot of libraries to `System.Diagnostics.Metrics`, because it is included by default in .NET 6+. As a consequence, we needed to drop support of App.Metrics and replaced it with OpenTelemetry. I'd be happy to switch back as soon as `System.Diagnostics.Metrics` is supported.

**Comment by EugeneKrapivin** [comment]
@dagophil This project is actually quite "dead". The author wrote (#755) that he doesn't have time to support this project and there is no point in doing so since the availability of `OpenTelemetry` and the impeccable support of `System.Diagnostics.Metrics`. 
Your migration to `System.Diagnostics.Metrics`, as it should be since it provides a standardized way for collecting metrics in your application/infrastructure code and the .NET framework, meaning your runtime and application metrics reside in the same repository, exported using the same method using the same naming schema.

**Comment by dagophil** [comment]
Oh, I did not know that. Thank you for the clarification.
